# ETG 0
- name: 'fibaro_door_sensor_laundry_room'
  icon: >-
    {% if is_state('binary_sensor.laundry_room_206_0_207', 'on') %}
      mdi:door-open
    {% else %}
      mdi:door
    {% endif %}
  state: >-
    {% if is_state('binary_sensor.laundry_room_206_0_207', 'on') %}
      Åpen
    {% else %}
      Lukket
    {% endif %}

- name: 'fibaro_door_sensor_battery_level_laundry_room:'
  device_class: 'battery'
  unit_of_measurement: "%"
  state: >-
    {{ state_attr('binary_sensor.laundry_room_206_0_207', 'battery_level') }}

- name: 'fibaro_door_sensor_technical_room'
  icon: >-
    {% if is_state('binary_sensor.technical_room_264_0_265', 'on') %}
      mdi:door-open
    {% else %}
      mdi:door
    {% endif %}
  state: >-
    {% if is_state('binary_sensor.technical_room_264_0_265', 'on') %}
      Åpen
    {% else %}
      Lukket
    {% endif %}

- name: 'fibaro_door_sensor_battery_level_technical_room'
  device_class: 'battery'
  unit_of_measurement: "%"
  state: >-
    {{ state_attr('binary_sensor.technical_room_264_0_265', 'battery_level') }}

# ETG 1
- name: 'fibaro_door_sensor_kitchen'
  icon: >-
    {% if is_state('binary_sensor.kitchen_258_0_259', 'on') %}
      mdi:arrow-right-bold-box-outline
    {% else %}
      mdi:checkbox-blank-outline
    {% endif %}
  state: >-
    {% if is_state('binary_sensor.kitchen_258_0_259', 'on') %}
      Åpen
    {% else %}
      Lukket
    {% endif %}

- name: 'fibaro_door_sensor_battery_level_kitchen'
  device_class: 'battery'
  unit_of_measurement: "%"
  state: >-
    {{ state_attr('binary_sensor.kitchen_258_0_259', 'battery_level') }}
