- name: 'switch_kitchen_325_0_326_power_w'
  icon: "mdi:silverware-clean"
  device_class: "power"
  unit_of_measurement: "W"
  state: >-
    {{ state_attr("switch.kitchen_325_0_326", "current_power_w") | float }}

- name: 'switch_kitchen_325_0_326_state'
  icon: "mdi:silverware-clean"
  state: >-
    {% if (state_attr("switch.kitchen_325_0_326", "current_power_w") > 3) %}
      Aktiv
    {% elif (state_attr("switch.kitchen_325_0_326", "current_power_w") > 1) %}
      PÃ¥
    {% else %}
      Av
    {% endif %}