# Stekeovn
- name: 'siemens_oven_status'
  icon: mdi:window-maximize
  state: >-
    {% if is_state("sensor.stekeovn_operation_state", "Ready") %}
      På
    {% elif is_state("sensor.stekeovn_operation_state", "Run") %}
      Aktiv
    {% elif is_state("sensor.stekeovn_operation_state", "Pause") %}
      Pauset
    {% elif is_state("sensor.stekeovn_operation_state", "Inactive") %}
      Av
    {% elif is_state("sensor.stekeovn_operation_state", "Delayedstart") %}
      Forsinket oppstart
    {% elif is_state("sensor.stekeovn_operation_state", "Actionrequired") %}
      Handling påkrevd
    {% elif is_state("sensor.stekeovn_operation_state", "Finished") %}
      Ferdig
    {% elif is_state("sensor.stekeovn_operation_state", "Error") %}
      Feil
    {% elif is_state("sensor.stekeovn_operation_state", "Aborting") %}
      Avbryter
    {% else %}
      Offline
    {% endif %}

- name: 'siemens_oven_program_progress'
  icon: mdi:progress-clock
  unit_of_measurement: "%"
  state: >-
    {{ states('sensor.stekeovn_program_progress') }}

- name: 'siemens_oven_remaining_program_time'
  icon: mdi:clock
  device_class: timestamp
  state: >-
    {{ states('sensor.stekeovn_remaining_program_time') }}

- name: 'siemens_oven_program'
  icon: mdi:book-open-outline
  state: >-
    {% if is_state("switch.stekeovn_program_600watt", "on") %}
      600watt
    {% elif is_state("switch.stekeovn_program_hotair", "on") %}
      4D-varmluft
    {% elif is_state("switch.stekeovn_program_pizzasetting", "on") %}
      Pizzainstilling
    {% elif is_state("switch.stekeovn_program_preheating", "on") %}
      Forvarming
    {% elif is_state("switch.stekeovn_program_topbottomheating", "on") %}
      Over-/undervarme
    {% else %}
      N/A
    {% endif %}

# Dampovn
- name: 'siemens_steam_oven_status'
  icon: mdi:dishwasher
  state: >-
    {% if is_state("sensor.dampovn_operation_state", "Ready") %}
      På
    {% elif is_state("sensor.dampovn_operation_state", "Run") %}
      Aktiv
    {% elif is_state("sensor.dampovn_operation_state", "Pause") %}
      Pauset
    {% elif is_state("sensor.dampovn_operation_state", "Inactive") %}
      Av
    {% elif is_state("sensor.dampovn_operation_state", "Delayedstart") %}
      Forsinket oppstart
    {% elif is_state("sensor.dampovn_operation_state", "Actionrequired") %}
      Handling påkrevd
    {% elif is_state("sensor.dampovn_operation_state", "Finished") %}
      Ferdig
    {% elif is_state("sensor.dampovn_operation_state", "Error") %}
      Feil
    {% elif is_state("sensor.dampovn_operation_state", "Aborting") %}
      Avbryter
    {% else %}
      Offline
    {% endif %}

- name: 'siemens_steam_oven_program_progress'
  icon: mdi:progress-clock
  unit_of_measurement: "%"
  state: >-
    {{ states('sensor.dampovn_program_progress') }}

- name: 'siemens_steam_oven_remaining_program_time'
  icon: mdi:clock
  device_class: timestamp
  state: >-
    {{ states('sensor.dampovn_remaining_program_time') }}

- name: 'siemens_steam_oven_program'
  icon: mdi:book-open-outline
  state: >-
    {% if is_state("switch.dampovn_program_hotair", "on") %}
      4D-varmluft
    {% elif is_state("switch.dampovn_program_pizzasetting", "on") %}
      Pizzainstilling
    {% elif is_state("switch.dampovn_program_preheating", "on") %}
      Forvarming
    {% elif is_state("switch.dampovn_program_topbottomheating", "on") %}
      Over-/undervarme
    {% else %}
      N/A
    {% endif %}

# Vaskemaskin
- name: 'bosch_washing_machine_status'
  icon: mdi:washing-machine
  state: >-
    {% if is_state("sensor.vaskemaskin_operation_state", "Ready") %}
      På
    {% elif is_state("sensor.vaskemaskin_operation_state", "Run") %}
      Aktiv
    {% elif is_state("sensor.vaskemaskin_operation_state", "Pause") %}
      Pauset
    {% elif is_state("sensor.vaskemaskin_operation_state", "Inactive") %}
      Av
    {% elif is_state("sensor.vaskemaskin_operation_state", "Delayedstart") %}
      Forsinket oppstart
    {% elif is_state("sensor.vaskemaskin_operation_state", "Actionrequired") %}
      Handling påkrevd
    {% elif is_state("sensor.vaskemaskin_operation_state", "Finished") %}
      Ferdig
    {% elif is_state("sensor.vaskemaskin_operation_state", "Error") %}
      Feil
    {% elif is_state("sensor.vaskemaskin_operation_state", "Aborting") %}
      Avbryter
    {% else %}
      Offline
    {% endif %}

- name: 'bosch_washing_machine_program_progress'
  icon: mdi:progress-clock
  unit_of_measurement: "%"
  state: >-
    {{ states('sensor.vaskemaskin_program_progress') }}

- name: 'bosch_washing_machine_remaining_program_time'
  icon: mdi:clock
  device_class: timestamp
  state: >-
    {{ states('sensor.vaskemaskin_remaining_program_time') }}

- name: 'bosch_washing_machine_program'
  icon: mdi:book-open-outline
  state: >-
    {% if is_state("switch.vaskemaskin_program_auto30", "on") %}
      Auto 30
    {% elif is_state("switch.vaskemaskin_program_auto40", "on") %}
      Auto 40
    {% elif is_state("switch.vaskemaskin_program_auto60", "on") %}
      Auto 60
    {% elif is_state("switch.vaskemaskin_program_chiffon", "on") %}
      Bluser
    {% elif is_state("switch.vaskemaskin_program_cotton", "on") %}
      Bomull
    {% elif is_state("switch.vaskemaskin_program_cottoneco", "on") %}
      Bomull Eco
    {% elif is_state("switch.vaskemaskin_program_curtains", "on") %}
      Gardiner
    {% elif is_state("switch.vaskemaskin_program_darkwash", "on") %}
      Mørk vask
    {% elif is_state("switch.vaskemaskin_program_delicatessilk", "on") %}
      Finvask/silke
    {% elif is_state("switch.vaskemaskin_program_dessous", "on") %}
      Dessous
    {% elif is_state("switch.vaskemaskin_program_easycare", "on") %}
      Lettstelt
    {% elif is_state("switch.vaskemaskin_program_mix", "on") %}
      Blandet
    {% elif is_state("switch.vaskemaskin_program_monsoon", "on") %}
      Monsun
    {% elif is_state("switch.vaskemaskin_program_outdoor", "on") %}
      Sportstøy
    {% elif is_state("switch.vaskemaskin_program_plushtoy", "on") %}
      Plush toy
    {% elif is_state("switch.vaskemaskin_program_sensitive", "on") %}
      Allergi pluss
    {% elif is_state("switch.vaskemaskin_program_shirtsblouses", "on") %}
      Skjorter/Bluser
    {% elif is_state("switch.vaskemaskin_program_sportfitness", "on") %}
      Sportstøy
    {% elif is_state("switch.vaskemaskin_program_towels", "on") %}
      Håndklær
    {% elif is_state("switch.vaskemaskin_program_waterproof", "on") %}
      Vanntett
    {% elif is_state("switch.vaskemaskin_program_wool", "on") %}
      Ull
    {% else %}
      N/A
    {% endif %}

# Tørketrommel
- name: 'bosch_tumble_dryer_status'
  icon: mdi:tumble-dryer
  state: >-
    {% if is_state("sensor.torketrommel_operation_state", "Ready") %}
      På
    {% elif is_state("sensor.torketrommel_operation_state", "Run") %}
      Aktiv
    {% elif is_state("sensor.torketrommel_operation_state", "Pause") %}
      Pauset
    {% elif is_state("sensor.torketrommel_operation_state", "Inactive") %}
      Av
    {% elif is_state("sensor.torketrommel_operation_state", "Delayedstart") %}
      Forsinket oppstart
    {% elif is_state("sensor.torketrommel_operation_state", "Actionrequired") %}
      Handling påkrevd
    {% elif is_state("sensor.torketrommel_operation_state", "Finished") %}
      Ferdig
    {% elif is_state("sensor.torketrommel_operation_state", "Error") %}
      Feil
    {% elif is_state("sensor.torketrommel_operation_state", "Aborting") %}
      Avbryter
    {% else %}
      Offline
    {% endif %}

- name: 'bosch_tumble_dryer_program_progress'
  icon: mdi:progress-clock
  unit_of_measurement: "%"
  state: >-
    {{ states('sensor.torketrommel_program_progress') }}

- name: 'bosch_tumble_dryer_remaining_program_time'
  icon: mdi:clock
  device_class: timestamp
  state: >-
    {{ states('sensor.torketrommel_remaining_program_time') }}

- name: 'bosch_tumble_dryer_program'
  icon: mdi:book-open-outline
  state: >-
    {% if is_state("switch.torketrommel_program_antishrink", "on") %}
      Antikrymp
    {% elif is_state("switch.torketrommel_program_blankets", "on") %}
      Dyner
    {% elif is_state("switch.torketrommel_program_businessshirts", "on") %}
      Skjorter/Bluser
    {% elif is_state("switch.torketrommel_program_cotton", "on") %}
      Bomull
    {% elif is_state("switch.torketrommel_program_delicates", "on") %}
      Finvask
    {% elif is_state("switch.torketrommel_program_downfeathers", "on") %}
      Dunplagg
    {% elif is_state("switch.torketrommel_program_hygiene", "on") %}
      Allergi pluss
    {% elif is_state("switch.torketrommel_program_jeans", "on") %}
      Jeans
    {% elif is_state("switch.torketrommel_program_mix", "on") %}
      Blandet
    {% elif is_state("switch.torketrommel_program_outdoor", "on") %}
      Sportstøy
    {% elif is_state("switch.torketrommel_program_pillow", "on") %}
      Puter
    {% elif is_state("switch.torketrommel_program_shirts15", "on") %}
      Skjorter 15
    {% elif is_state("switch.torketrommel_program_super40", "on") %}
      Super Quick 40
    {% elif is_state("switch.torketrommel_program_synthetic", "on") %}
      Lettstelt
    {% elif is_state("switch.torketrommel_program_syntheticrefresh", "on") %}
      Lettstelt refresh
    {% elif is_state("switch.torketrommel_program_towels", "on") %}
      Håndklær
    {% else %}
      N/A
    {% endif %}