# Stekeovn
- name: 'siemens_oven_door'
  device_class: door
  state: >-
    {{ states('binary_sensor.stekeovn_door') }}

# Dampovn
- name: 'siemens_steam_oven_door'
  device_class: door
  state: >-
    {{ states('binary_sensor.dampovn_door') }}

# Vaskemaskin
- name: 'bosch_washing_machine_door'
  device_class: door
  state: >-
    {{ states('binary_sensor.vaskemaskin_door') }}

# TÃ¸rketrommel
- name: 'bosch_tumble_dryer_door'
  device_class: door
  state: >-
    {{ states('binary_sensor.torketrommel_door') }}