# Stekeovn
sensor.siemens_oven_status:
  friendly_name: Stekeovn

sensor.siemens_oven_program_progress:
  friendly_name: Status

sensor.siemens_oven_remaining_program_time:
  friendly_name: Gjenstående

sensor.siemens_oven_program:
  friendly_name: Program

binary_sensor.siemens_oven_door:
  friendly_name: Dør

# Dampovn
sensor.siemens_steam_oven_status:
  friendly_name: Dampovn

sensor.siemens_steam_oven_program_progress:
  friendly_name: Status

sensor.siemens_steam_oven_remaining_program_time:
  friendly_name: Gjenstående

sensor.siemens_steam_oven_program:
  friendly_name: Program

binary_sensor.siemens_steam_oven_door:
  friendly_name: Dør

# Vaskemaskin
sensor.bosch_washing_machine_status:
  friendly_name: Vaskemaskin

sensor.bosch_washing_machine_program_progress:
  friendly_name: Status

sensor.bosch_washing_machine_remaining_program_time:
  friendly_name: Gjenstående

sensor.bosch_washing_machine_program:
  friendly_name: Program

binary_sensor.bosch_washing_machine_door:
  friendly_name: Dør

# Tørketrommel
sensor.bosch_tumble_dryer_status:
  friendly_name: Tørketrommel

sensor.bosch_tumble_dryer_program_progress:
  friendly_name: Status

sensor.bosch_tumble_dryer_remaining_program_time:
  friendly_name: Gjenstående

sensor.bosch_tumble_dryer_program:
  friendly_name: Program

binary_sensor.bosch_tumble_dryer_door:
  friendly_name: Dør